/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const JournalEntry = IDL.Record({
  'content' : IDL.Text,
  'date' : Time,
  'createdAt' : Time,
});
export const RelationshipIntent = IDL.Variant({
  'romantic' : IDL.Null,
  'both' : IDL.Null,
  'friendship' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'nonBinary' : IDL.Null,
});
export const Preferences = IDL.Record({
  'intent' : RelationshipIntent,
  'gender' : Gender,
});
export const UploadedAvatar = IDL.Record({
  'contentType' : IDL.Text,
  'image' : IDL.Vec(IDL.Nat8),
});
export const Avatar = IDL.Variant({
  'uploaded' : UploadedAvatar,
  'systemAvatar' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'dateOfBirth' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'preferences' : Preferences,
  'showAge' : IDL.Bool,
  'relationshipIntent' : RelationshipIntent,
  'gender' : Gender,
  'shareCode' : IDL.Text,
  'avatar' : IDL.Opt(Avatar),
});
export const Mood = IDL.Variant({
  'joy' : IDL.Null,
  'sad' : IDL.Null,
  'shy' : IDL.Null,
  'zen' : IDL.Null,
  'hopeful' : IDL.Null,
  'inspiration' : IDL.Null,
  'tired' : IDL.Null,
  'content' : IDL.Null,
  'anxious' : IDL.Null,
  'courage' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'triumph' : IDL.Null,
  'nervous' : IDL.Null,
  'embarrass' : IDL.Null,
  'apathetic' : IDL.Null,
  'melancholy' : IDL.Null,
  'bore' : IDL.Null,
  'calm' : IDL.Null,
  'fear' : IDL.Null,
  'irritate' : IDL.Null,
  'relaxed' : IDL.Null,
  'grateful' : IDL.Null,
  'lonely' : IDL.Null,
  'secure' : IDL.Null,
  'unsafe' : IDL.Null,
  'satisfy' : IDL.Null,
  'motivate' : IDL.Null,
  'stressed' : IDL.Null,
  'frustrate' : IDL.Null,
  'overwhelm' : IDL.Null,
  'passionate' : IDL.Null,
  'disappoint' : IDL.Null,
  'excited' : IDL.Null,
  'indifferen' : IDL.Null,
  'humbled' : IDL.Null,
  'disgust' : IDL.Null,
  'confident' : IDL.Null,
  'curious' : IDL.Null,
  'relieved' : IDL.Null,
  'worry' : IDL.Null,
  'guilty' : IDL.Null,
  'ashamed' : IDL.Null,
  'neutral' : IDL.Null,
  'optimistic' : IDL.Null,
});
export const StatusPost = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'contextTags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'mood' : Mood,
  'createdAt' : Time,
  'audience' : IDL.Vec(IDL.Principal),
  'author' : IDL.Principal,
});
export const SilentSignal = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'mood' : Mood,
  'createdAt' : Time,
  'audience' : IDL.Vec(IDL.Principal),
  'author' : IDL.Principal,
});
export const FeedItem = IDL.Variant({
  'status' : StatusPost,
  'silentSignal' : SilentSignal,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'isRead' : IDL.Bool,
  'statusId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'requesterName' : IDL.Opt(IDL.Text),
});
export const JoinRequest = IDL.Record({
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'createdAt' : Time,
  'shareCode' : IDL.Text,
});
export const PendingRequestWithProfile = IDL.Record({
  'request' : JoinRequest,
  'profile' : UserProfile,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptJoinRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateJournalEntry' : IDL.Func([IDL.Text], [], []),
  'declineJoinRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'deleteJournalEntry' : IDL.Func([Time], [], []),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCircleMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getEligibleSafePeopleCandidates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getEntriesByRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'getFeed' : IDL.Func([], [IDL.Vec(FeedItem)], ['query']),
  'getJournalEntry' : IDL.Func([Time], [IDL.Opt(JournalEntry)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOwnSilentSignals' : IDL.Func([], [IDL.Vec(SilentSignal)], ['query']),
  'getSafePeople' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getShareCodeByPrincipal' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getSilentSignals' : IDL.Func([], [IDL.Vec(SilentSignal)], ['query']),
  'getStatus' : IDL.Func([IDL.Text], [IDL.Opt(StatusPost)], ['query']),
  'getUnprocessedJoinRequests' : IDL.Func(
      [],
      [IDL.Vec(PendingRequestWithProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCircleFromShareCode' : IDL.Func([IDL.Text], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'postSilentSignal' : IDL.Func([Mood, IDL.Text], [], []),
  'postStatus' : IDL.Func([StatusPost], [], []),
  'removeCircleMember' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectSystemAvatar' : IDL.Func([IDL.Text], [], []),
  'setSafePerson' : IDL.Func([IDL.Principal], [], []),
  'unsetSafePerson' : IDL.Func([IDL.Principal], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
  'updateShareCode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'uploadAvatar' : IDL.Func([UploadedAvatar], [], []),
  'viewProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const JournalEntry = IDL.Record({
    'content' : IDL.Text,
    'date' : Time,
    'createdAt' : Time,
  });
  const RelationshipIntent = IDL.Variant({
    'romantic' : IDL.Null,
    'both' : IDL.Null,
    'friendship' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'nonBinary' : IDL.Null,
  });
  const Preferences = IDL.Record({
    'intent' : RelationshipIntent,
    'gender' : Gender,
  });
  const UploadedAvatar = IDL.Record({
    'contentType' : IDL.Text,
    'image' : IDL.Vec(IDL.Nat8),
  });
  const Avatar = IDL.Variant({
    'uploaded' : UploadedAvatar,
    'systemAvatar' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'dateOfBirth' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'preferences' : Preferences,
    'showAge' : IDL.Bool,
    'relationshipIntent' : RelationshipIntent,
    'gender' : Gender,
    'shareCode' : IDL.Text,
    'avatar' : IDL.Opt(Avatar),
  });
  const Mood = IDL.Variant({
    'joy' : IDL.Null,
    'sad' : IDL.Null,
    'shy' : IDL.Null,
    'zen' : IDL.Null,
    'hopeful' : IDL.Null,
    'inspiration' : IDL.Null,
    'tired' : IDL.Null,
    'content' : IDL.Null,
    'anxious' : IDL.Null,
    'courage' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'triumph' : IDL.Null,
    'nervous' : IDL.Null,
    'embarrass' : IDL.Null,
    'apathetic' : IDL.Null,
    'melancholy' : IDL.Null,
    'bore' : IDL.Null,
    'calm' : IDL.Null,
    'fear' : IDL.Null,
    'irritate' : IDL.Null,
    'relaxed' : IDL.Null,
    'grateful' : IDL.Null,
    'lonely' : IDL.Null,
    'secure' : IDL.Null,
    'unsafe' : IDL.Null,
    'satisfy' : IDL.Null,
    'motivate' : IDL.Null,
    'stressed' : IDL.Null,
    'frustrate' : IDL.Null,
    'overwhelm' : IDL.Null,
    'passionate' : IDL.Null,
    'disappoint' : IDL.Null,
    'excited' : IDL.Null,
    'indifferen' : IDL.Null,
    'humbled' : IDL.Null,
    'disgust' : IDL.Null,
    'confident' : IDL.Null,
    'curious' : IDL.Null,
    'relieved' : IDL.Null,
    'worry' : IDL.Null,
    'guilty' : IDL.Null,
    'ashamed' : IDL.Null,
    'neutral' : IDL.Null,
    'optimistic' : IDL.Null,
  });
  const StatusPost = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'contextTags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'mood' : Mood,
    'createdAt' : Time,
    'audience' : IDL.Vec(IDL.Principal),
    'author' : IDL.Principal,
  });
  const SilentSignal = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'mood' : Mood,
    'createdAt' : Time,
    'audience' : IDL.Vec(IDL.Principal),
    'author' : IDL.Principal,
  });
  const FeedItem = IDL.Variant({
    'status' : StatusPost,
    'silentSignal' : SilentSignal,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'isRead' : IDL.Bool,
    'statusId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'requesterName' : IDL.Opt(IDL.Text),
  });
  const JoinRequest = IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'createdAt' : Time,
    'shareCode' : IDL.Text,
  });
  const PendingRequestWithProfile = IDL.Record({
    'request' : JoinRequest,
    'profile' : UserProfile,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptJoinRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateJournalEntry' : IDL.Func([IDL.Text], [], []),
    'declineJoinRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'deleteJournalEntry' : IDL.Func([Time], [], []),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCircleMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getEligibleSafePeopleCandidates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getEntriesByRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getFeed' : IDL.Func([], [IDL.Vec(FeedItem)], ['query']),
    'getJournalEntry' : IDL.Func([Time], [IDL.Opt(JournalEntry)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOwnSilentSignals' : IDL.Func([], [IDL.Vec(SilentSignal)], ['query']),
    'getSafePeople' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getShareCodeByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Text],
        ['query'],
      ),
    'getSilentSignals' : IDL.Func([], [IDL.Vec(SilentSignal)], ['query']),
    'getStatus' : IDL.Func([IDL.Text], [IDL.Opt(StatusPost)], ['query']),
    'getUnprocessedJoinRequests' : IDL.Func(
        [],
        [IDL.Vec(PendingRequestWithProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCircleFromShareCode' : IDL.Func([IDL.Text], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'postSilentSignal' : IDL.Func([Mood, IDL.Text], [], []),
    'postStatus' : IDL.Func([StatusPost], [], []),
    'removeCircleMember' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectSystemAvatar' : IDL.Func([IDL.Text], [], []),
    'setSafePerson' : IDL.Func([IDL.Principal], [], []),
    'unsetSafePerson' : IDL.Func([IDL.Principal], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
    'updateShareCode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'uploadAvatar' : IDL.Func([UploadedAvatar], [], []),
    'viewProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };