/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Avatar = { 'uploaded' : UploadedAvatar } |
  { 'systemAvatar' : string };
export type FeedItem = { 'status' : StatusPost } |
  { 'silentSignal' : SilentSignal };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null } |
  { 'nonBinary' : null };
export interface JoinRequest {
  'to' : Principal,
  'from' : Principal,
  'createdAt' : Time,
  'shareCode' : string,
}
export interface JournalEntry {
  'content' : string,
  'date' : Time,
  'createdAt' : Time,
}
export type Mood = { 'joy' : null } |
  { 'sad' : null } |
  { 'shy' : null } |
  { 'zen' : null } |
  { 'hopeful' : null } |
  { 'inspiration' : null } |
  { 'tired' : null } |
  { 'content' : null } |
  { 'anxious' : null } |
  { 'courage' : null } |
  { 'happy' : null } |
  { 'angry' : null } |
  { 'triumph' : null } |
  { 'nervous' : null } |
  { 'embarrass' : null } |
  { 'apathetic' : null } |
  { 'melancholy' : null } |
  { 'bore' : null } |
  { 'calm' : null } |
  { 'fear' : null } |
  { 'irritate' : null } |
  { 'relaxed' : null } |
  { 'grateful' : null } |
  { 'lonely' : null } |
  { 'secure' : null } |
  { 'unsafe' : null } |
  { 'satisfy' : null } |
  { 'motivate' : null } |
  { 'stressed' : null } |
  { 'frustrate' : null } |
  { 'overwhelm' : null } |
  { 'passionate' : null } |
  { 'disappoint' : null } |
  { 'excited' : null } |
  { 'indifferen' : null } |
  { 'humbled' : null } |
  { 'disgust' : null } |
  { 'confident' : null } |
  { 'curious' : null } |
  { 'relieved' : null } |
  { 'worry' : null } |
  { 'guilty' : null } |
  { 'ashamed' : null } |
  { 'neutral' : null } |
  { 'optimistic' : null };
export interface Notification {
  'id' : string,
  'createdAt' : Time,
  'user' : Principal,
  'isRead' : boolean,
  'statusId' : [] | [string],
  'message' : string,
  'requesterName' : [] | [string],
}
export interface PendingRequestWithProfile {
  'request' : JoinRequest,
  'profile' : UserProfile,
}
export interface Preferences {
  'intent' : RelationshipIntent,
  'gender' : Gender,
}
export type RelationshipIntent = { 'romantic' : null } |
  { 'both' : null } |
  { 'friendship' : null };
export interface SilentSignal {
  'id' : string,
  'content' : string,
  'mood' : Mood,
  'createdAt' : Time,
  'audience' : Array<Principal>,
  'author' : Principal,
}
export interface StatusPost {
  'id' : string,
  'content' : string,
  'contextTags' : [] | [Array<string>],
  'mood' : Mood,
  'createdAt' : Time,
  'audience' : Array<Principal>,
  'author' : Principal,
}
export type Time = bigint;
export interface UploadedAvatar { 'contentType' : string, 'image' : Uint8Array }
export interface UserProfile {
  'dateOfBirth' : bigint,
  'name' : string,
  'createdAt' : Time,
  'preferences' : Preferences,
  'showAge' : boolean,
  'relationshipIntent' : RelationshipIntent,
  'gender' : Gender,
  'shareCode' : string,
  'avatar' : [] | [Avatar],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptJoinRequest' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateJournalEntry' : ActorMethod<[string], undefined>,
  'declineJoinRequest' : ActorMethod<[Principal, string], undefined>,
  'deleteJournalEntry' : ActorMethod<[Time], undefined>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCircleMembers' : ActorMethod<[], Array<Principal>>,
  'getEligibleSafePeopleCandidates' : ActorMethod<[], Array<Principal>>,
  'getEntriesByRange' : ActorMethod<[Time, Time], Array<JournalEntry>>,
  'getFeed' : ActorMethod<[], Array<FeedItem>>,
  'getJournalEntry' : ActorMethod<[Time], [] | [JournalEntry]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getOwnSilentSignals' : ActorMethod<[], Array<SilentSignal>>,
  'getSafePeople' : ActorMethod<[], Array<Principal>>,
  'getShareCodeByPrincipal' : ActorMethod<[Principal], string>,
  'getSilentSignals' : ActorMethod<[], Array<SilentSignal>>,
  'getStatus' : ActorMethod<[string], [] | [StatusPost]>,
  'getUnprocessedJoinRequests' : ActorMethod<
    [],
    Array<PendingRequestWithProfile>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinCircleFromShareCode' : ActorMethod<[string], undefined>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'postSilentSignal' : ActorMethod<[Mood, string], undefined>,
  'postStatus' : ActorMethod<[StatusPost], undefined>,
  'removeCircleMember' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectSystemAvatar' : ActorMethod<[string], undefined>,
  'setSafePerson' : ActorMethod<[Principal], undefined>,
  'unsetSafePerson' : ActorMethod<[Principal], undefined>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
  'updateShareCode' : ActorMethod<[string], string>,
  'uploadAvatar' : ActorMethod<[UploadedAvatar], undefined>,
  'viewProfile' : ActorMethod<[Principal], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];