/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type Avatar = {
    __kind__: "uploaded";
    uploaded: UploadedAvatar;
} | {
    __kind__: "systemAvatar";
    systemAvatar: string;
};
export interface Preferences {
    intent: RelationshipIntent;
    gender: Gender;
}
export interface UpdateUserProfile {
    preferences: Preferences;
    showAge: boolean;
    relationshipIntent: RelationshipIntent;
    shareCode: string;
}
export interface StatusPost {
    id: string;
    content: string;
    contextTags?: Array<string>;
    mood: Mood;
    createdAt: Time;
    audience: Array<Principal>;
    author: Principal;
}
export interface PendingRequestWithProfile {
    request: JoinRequest;
    profile: UserProfile;
}
export interface JournalEntry {
    content: string;
    date: Time;
    createdAt: Time;
}
export interface Notification {
    id: string;
    createdAt: Time;
    user: Principal;
    isRead: boolean;
    statusId?: string;
    message: string;
    requesterName?: string;
}
export type FeedItem = {
    __kind__: "status";
    status: StatusPost;
} | {
    __kind__: "silentSignal";
    silentSignal: SilentSignal;
};
export interface UploadedAvatar {
    contentType: string;
    image: Uint8Array;
}
export interface ConnectionWhyExplanation {
    why: string;
    principal: Principal;
    interaction: bigint;
    name: string;
    sharedConnections: bigint;
}
export interface SilentSignal {
    id: string;
    content: string;
    mood: Mood;
    createdAt: Time;
    audience: Array<Principal>;
    author: Principal;
}
export interface JoinRequest {
    to: Principal;
    from: Principal;
    createdAt: Time;
    shareCode: string;
}
export interface UserProfile {
    dateOfBirth: bigint;
    name: string;
    createdAt: Time;
    preferences: Preferences;
    showAge: boolean;
    relationshipIntent: RelationshipIntent;
    gender: Gender;
    shareCode: string;
    avatar?: Avatar;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male",
    nonBinary = "nonBinary"
}
export enum Mood {
    joy = "joy",
    sad = "sad",
    shy = "shy",
    zen = "zen",
    hopeful = "hopeful",
    inspiration = "inspiration",
    tired = "tired",
    content = "content",
    anxious = "anxious",
    courage = "courage",
    happy = "happy",
    angry = "angry",
    triumph = "triumph",
    nervous = "nervous",
    embarrass = "embarrass",
    apathetic = "apathetic",
    melancholy = "melancholy",
    bore = "bore",
    calm = "calm",
    fear = "fear",
    irritate = "irritate",
    relaxed = "relaxed",
    grateful = "grateful",
    lonely = "lonely",
    secure = "secure",
    unsafe = "unsafe",
    satisfy = "satisfy",
    motivate = "motivate",
    stressed = "stressed",
    frustrate = "frustrate",
    overwhelm = "overwhelm",
    passionate = "passionate",
    disappoint = "disappoint",
    excited = "excited",
    indifferen = "indifferen",
    humbled = "humbled",
    disgust = "disgust",
    confident = "confident",
    curious = "curious",
    relieved = "relieved",
    worry = "worry",
    guilty = "guilty",
    ashamed = "ashamed",
    neutral = "neutral",
    optimistic = "optimistic"
}
export enum RelationshipIntent {
    romantic = "romantic",
    both = "both",
    friendship = "friendship"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptJoinRequest(from: Principal, code: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateJournalEntry(content: string): Promise<void>;
    declineJoinRequest(user: Principal, code: string): Promise<void>;
    deleteJournalEntry(date: Time): Promise<void>;
    getAllJournalEntries(): Promise<Array<JournalEntry>>;
    getBestCircleConnectionsWithWhyExplanation(): Promise<Array<ConnectionWhyExplanation>>;
    getCallerCircleOwners(): Promise<Array<Principal>>;
    getCallerPulseScore(): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCircleMembers(): Promise<Array<Principal>>;
    getEligibleSafePeopleCandidates(): Promise<Array<Principal>>;
    getEntriesByRange(startDate: Time, endDate: Time): Promise<Array<JournalEntry>>;
    getFeed(): Promise<Array<FeedItem>>;
    getJournalEntry(date: Time): Promise<JournalEntry | null>;
    getNotifications(): Promise<Array<Notification>>;
    getOwnSilentSignals(): Promise<Array<SilentSignal>>;
    getSafePeople(): Promise<Array<Principal>>;
    getShareCodeByPrincipal(principal: Principal): Promise<string>;
    getSilentSignals(): Promise<Array<SilentSignal>>;
    getStatus(statusId: string): Promise<StatusPost | null>;
    getUnprocessedJoinRequests(): Promise<Array<PendingRequestWithProfile>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserPulseScore(user: Principal): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    joinCircleFromShareCode(code: string): Promise<void>;
    postSilentSignal(mood: Mood, content: string): Promise<void>;
    postStatus(status: StatusPost): Promise<void>;
    removeCircleMember(member: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selectSystemAvatar(avatarId: string): Promise<void>;
    setSafePerson(person: Principal): Promise<void>;
    unsetSafePerson(person: Principal): Promise<void>;
    updateProfile(updates: UpdateUserProfile): Promise<void>;
    updateShareCode(code: string): Promise<string>;
    uploadAvatar(avatar: UploadedAvatar): Promise<void>;
    viewProfile(id: Principal): Promise<UserProfile>;
}
import type { Avatar as _Avatar, FeedItem as _FeedItem, Gender as _Gender, JoinRequest as _JoinRequest, JournalEntry as _JournalEntry, Mood as _Mood, Notification as _Notification, PendingRequestWithProfile as _PendingRequestWithProfile, Preferences as _Preferences, RelationshipIntent as _RelationshipIntent, SilentSignal as _SilentSignal, StatusPost as _StatusPost, Time as _Time, UpdateUserProfile as _UpdateUserProfile, UploadedAvatar as _UploadedAvatar, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptJoinRequest(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptJoinRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptJoinRequest(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateJournalEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateJournalEntry(arg0);
            return result;
        }
    }
    async declineJoinRequest(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineJoinRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineJoinRequest(arg0, arg1);
            return result;
        }
    }
    async deleteJournalEntry(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async getAllJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalEntries();
            return result;
        }
    }
    async getBestCircleConnectionsWithWhyExplanation(): Promise<Array<ConnectionWhyExplanation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestCircleConnectionsWithWhyExplanation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestCircleConnectionsWithWhyExplanation();
            return result;
        }
    }
    async getCallerCircleOwners(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerCircleOwners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerCircleOwners();
            return result;
        }
    }
    async getCallerPulseScore(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPulseScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPulseScore();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCircleMembers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCircleMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCircleMembers();
            return result;
        }
    }
    async getEligibleSafePeopleCandidates(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEligibleSafePeopleCandidates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEligibleSafePeopleCandidates();
            return result;
        }
    }
    async getEntriesByRange(arg0: Time, arg1: Time): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByRange(arg0, arg1);
            return result;
        }
    }
    async getFeed(): Promise<Array<FeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalEntry(arg0: Time): Promise<JournalEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntry(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntry(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnSilentSignals(): Promise<Array<SilentSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnSilentSignals();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnSilentSignals();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSafePeople(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafePeople();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafePeople();
            return result;
        }
    }
    async getShareCodeByPrincipal(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareCodeByPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareCodeByPrincipal(arg0);
            return result;
        }
    }
    async getSilentSignals(): Promise<Array<SilentSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSilentSignals();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSilentSignals();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatus(arg0: string): Promise<StatusPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatus(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatus(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnprocessedJoinRequests(): Promise<Array<PendingRequestWithProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnprocessedJoinRequests();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnprocessedJoinRequests();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPulseScore(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPulseScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPulseScore(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinCircleFromShareCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCircleFromShareCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCircleFromShareCode(arg0);
            return result;
        }
    }
    async postSilentSignal(arg0: Mood, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postSilentSignal(to_candid_Mood_n37(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postSilentSignal(to_candid_Mood_n37(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async postStatus(arg0: StatusPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postStatus(to_candid_StatusPost_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postStatus(to_candid_StatusPost_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async removeCircleMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCircleMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCircleMember(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async selectSystemAvatar(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectSystemAvatar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectSystemAvatar(arg0);
            return result;
        }
    }
    async setSafePerson(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSafePerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSafePerson(arg0);
            return result;
        }
    }
    async unsetSafePerson(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsetSafePerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsetSafePerson(arg0);
            return result;
        }
    }
    async updateProfile(arg0: UpdateUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UpdateUserProfile_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UpdateUserProfile_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateShareCode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShareCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShareCode(arg0);
            return result;
        }
    }
    async uploadAvatar(arg0: UploadedAvatar): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAvatar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAvatar(arg0);
            return result;
        }
    }
    async viewProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.viewProfile(arg0);
                return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewProfile(arg0);
            return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Avatar_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Avatar): Avatar {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_FeedItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedItem): FeedItem {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Mood_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PendingRequestWithProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PendingRequestWithProfile): PendingRequestWithProfile {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Preferences_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Preferences): Preferences {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RelationshipIntent_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RelationshipIntent): RelationshipIntent {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SilentSignal_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SilentSignal): SilentSignal {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StatusPost_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusPost): StatusPost {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Avatar]): Avatar | null {
    return value.length === 0 ? null : from_candid_Avatar_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JournalEntry]): JournalEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StatusPost]): StatusPost | null {
    return value.length === 0 ? null : from_candid_StatusPost_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    contextTags: [] | [Array<string>];
    mood: _Mood;
    createdAt: _Time;
    audience: Array<Principal>;
    author: Principal;
}): {
    id: string;
    content: string;
    contextTags?: Array<string>;
    mood: Mood;
    createdAt: Time;
    audience: Array<Principal>;
    author: Principal;
} {
    return {
        id: value.id,
        content: value.content,
        contextTags: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.contextTags)),
        mood: from_candid_Mood_n23(_uploadFile, _downloadFile, value.mood),
        createdAt: value.createdAt,
        audience: value.audience,
        author: value.author
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    mood: _Mood;
    createdAt: _Time;
    audience: Array<Principal>;
    author: Principal;
}): {
    id: string;
    content: string;
    mood: Mood;
    createdAt: Time;
    audience: Array<Principal>;
    author: Principal;
} {
    return {
        id: value.id,
        content: value.content,
        mood: from_candid_Mood_n23(_uploadFile, _downloadFile, value.mood),
        createdAt: value.createdAt,
        audience: value.audience,
        author: value.author
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: _Time;
    user: Principal;
    isRead: boolean;
    statusId: [] | [string];
    message: string;
    requesterName: [] | [string];
}): {
    id: string;
    createdAt: Time;
    user: Principal;
    isRead: boolean;
    statusId?: string;
    message: string;
    requesterName?: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        user: value.user,
        isRead: value.isRead,
        statusId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.statusId)),
        message: value.message,
        requesterName: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.requesterName))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    request: _JoinRequest;
    profile: _UserProfile;
}): {
    request: JoinRequest;
    profile: UserProfile;
} {
    return {
        request: value.request,
        profile: from_candid_UserProfile_n4(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: bigint;
    name: string;
    createdAt: _Time;
    preferences: _Preferences;
    showAge: boolean;
    relationshipIntent: _RelationshipIntent;
    gender: _Gender;
    shareCode: string;
    avatar: [] | [_Avatar];
}): {
    dateOfBirth: bigint;
    name: string;
    createdAt: Time;
    preferences: Preferences;
    showAge: boolean;
    relationshipIntent: RelationshipIntent;
    gender: Gender;
    shareCode: string;
    avatar?: Avatar;
} {
    return {
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        createdAt: value.createdAt,
        preferences: from_candid_Preferences_n6(_uploadFile, _downloadFile, value.preferences),
        showAge: value.showAge,
        relationshipIntent: from_candid_RelationshipIntent_n8(_uploadFile, _downloadFile, value.relationshipIntent),
        gender: from_candid_Gender_n10(_uploadFile, _downloadFile, value.gender),
        shareCode: value.shareCode,
        avatar: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intent: _RelationshipIntent;
    gender: _Gender;
}): {
    intent: RelationshipIntent;
    gender: Gender;
} {
    return {
        intent: from_candid_RelationshipIntent_n8(_uploadFile, _downloadFile, value.intent),
        gender: from_candid_Gender_n10(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    nonBinary: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : "nonBinary" in value ? Gender.nonBinary : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uploaded: _UploadedAvatar;
} | {
    systemAvatar: string;
}): {
    __kind__: "uploaded";
    uploaded: UploadedAvatar;
} | {
    __kind__: "systemAvatar";
    systemAvatar: string;
} {
    return "uploaded" in value ? {
        __kind__: "uploaded",
        uploaded: value.uploaded
    } : "systemAvatar" in value ? {
        __kind__: "systemAvatar",
        systemAvatar: value.systemAvatar
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _StatusPost;
} | {
    silentSignal: _SilentSignal;
}): {
    __kind__: "status";
    status: StatusPost;
} | {
    __kind__: "silentSignal";
    silentSignal: SilentSignal;
} {
    return "status" in value ? {
        __kind__: "status",
        status: from_candid_StatusPost_n20(_uploadFile, _downloadFile, value.status)
    } : "silentSignal" in value ? {
        __kind__: "silentSignal",
        silentSignal: from_candid_SilentSignal_n25(_uploadFile, _downloadFile, value.silentSignal)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    joy: null;
} | {
    sad: null;
} | {
    shy: null;
} | {
    zen: null;
} | {
    hopeful: null;
} | {
    inspiration: null;
} | {
    tired: null;
} | {
    content: null;
} | {
    anxious: null;
} | {
    courage: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    triumph: null;
} | {
    nervous: null;
} | {
    embarrass: null;
} | {
    apathetic: null;
} | {
    melancholy: null;
} | {
    bore: null;
} | {
    calm: null;
} | {
    fear: null;
} | {
    irritate: null;
} | {
    relaxed: null;
} | {
    grateful: null;
} | {
    lonely: null;
} | {
    secure: null;
} | {
    unsafe: null;
} | {
    satisfy: null;
} | {
    motivate: null;
} | {
    stressed: null;
} | {
    frustrate: null;
} | {
    overwhelm: null;
} | {
    passionate: null;
} | {
    disappoint: null;
} | {
    excited: null;
} | {
    indifferen: null;
} | {
    humbled: null;
} | {
    disgust: null;
} | {
    confident: null;
} | {
    curious: null;
} | {
    relieved: null;
} | {
    worry: null;
} | {
    guilty: null;
} | {
    ashamed: null;
} | {
    neutral: null;
} | {
    optimistic: null;
}): Mood {
    return "joy" in value ? Mood.joy : "sad" in value ? Mood.sad : "shy" in value ? Mood.shy : "zen" in value ? Mood.zen : "hopeful" in value ? Mood.hopeful : "inspiration" in value ? Mood.inspiration : "tired" in value ? Mood.tired : "content" in value ? Mood.content : "anxious" in value ? Mood.anxious : "courage" in value ? Mood.courage : "happy" in value ? Mood.happy : "angry" in value ? Mood.angry : "triumph" in value ? Mood.triumph : "nervous" in value ? Mood.nervous : "embarrass" in value ? Mood.embarrass : "apathetic" in value ? Mood.apathetic : "melancholy" in value ? Mood.melancholy : "bore" in value ? Mood.bore : "calm" in value ? Mood.calm : "fear" in value ? Mood.fear : "irritate" in value ? Mood.irritate : "relaxed" in value ? Mood.relaxed : "grateful" in value ? Mood.grateful : "lonely" in value ? Mood.lonely : "secure" in value ? Mood.secure : "unsafe" in value ? Mood.unsafe : "satisfy" in value ? Mood.satisfy : "motivate" in value ? Mood.motivate : "stressed" in value ? Mood.stressed : "frustrate" in value ? Mood.frustrate : "overwhelm" in value ? Mood.overwhelm : "passionate" in value ? Mood.passionate : "disappoint" in value ? Mood.disappoint : "excited" in value ? Mood.excited : "indifferen" in value ? Mood.indifferen : "humbled" in value ? Mood.humbled : "disgust" in value ? Mood.disgust : "confident" in value ? Mood.confident : "curious" in value ? Mood.curious : "relieved" in value ? Mood.relieved : "worry" in value ? Mood.worry : "guilty" in value ? Mood.guilty : "ashamed" in value ? Mood.ashamed : "neutral" in value ? Mood.neutral : "optimistic" in value ? Mood.optimistic : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    romantic: null;
} | {
    both: null;
} | {
    friendship: null;
}): RelationshipIntent {
    return "romantic" in value ? RelationshipIntent.romantic : "both" in value ? RelationshipIntent.both : "friendship" in value ? RelationshipIntent.friendship : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedItem>): Array<FeedItem> {
    return value.map((x)=>from_candid_FeedItem_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SilentSignal>): Array<SilentSignal> {
    return value.map((x)=>from_candid_SilentSignal_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PendingRequestWithProfile>): Array<PendingRequestWithProfile> {
    return value.map((x)=>from_candid_PendingRequestWithProfile_n35(_uploadFile, _downloadFile, x));
}
function to_candid_Avatar_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Avatar): _Avatar {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_Mood_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Preferences_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Preferences): _Preferences {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_RelationshipIntent_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RelationshipIntent): _RelationshipIntent {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_StatusPost_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusPost): _StatusPost {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUserProfile): _UpdateUserProfile {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    contextTags?: Array<string>;
    mood: Mood;
    createdAt: Time;
    audience: Array<Principal>;
    author: Principal;
}): {
    id: string;
    content: string;
    contextTags: [] | [Array<string>];
    mood: _Mood;
    createdAt: _Time;
    audience: Array<Principal>;
    author: Principal;
} {
    return {
        id: value.id,
        content: value.content,
        contextTags: value.contextTags ? candid_some(value.contextTags) : candid_none(),
        mood: to_candid_Mood_n37(_uploadFile, _downloadFile, value.mood),
        createdAt: value.createdAt,
        audience: value.audience,
        author: value.author
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: bigint;
    name: string;
    createdAt: Time;
    preferences: Preferences;
    showAge: boolean;
    relationshipIntent: RelationshipIntent;
    gender: Gender;
    shareCode: string;
    avatar?: Avatar;
}): {
    dateOfBirth: bigint;
    name: string;
    createdAt: _Time;
    preferences: _Preferences;
    showAge: boolean;
    relationshipIntent: _RelationshipIntent;
    gender: _Gender;
    shareCode: string;
    avatar: [] | [_Avatar];
} {
    return {
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        createdAt: value.createdAt,
        preferences: to_candid_Preferences_n43(_uploadFile, _downloadFile, value.preferences),
        showAge: value.showAge,
        relationshipIntent: to_candid_RelationshipIntent_n45(_uploadFile, _downloadFile, value.relationshipIntent),
        gender: to_candid_Gender_n47(_uploadFile, _downloadFile, value.gender),
        shareCode: value.shareCode,
        avatar: value.avatar ? candid_some(to_candid_Avatar_n49(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intent: RelationshipIntent;
    gender: Gender;
}): {
    intent: _RelationshipIntent;
    gender: _Gender;
} {
    return {
        intent: to_candid_RelationshipIntent_n45(_uploadFile, _downloadFile, value.intent),
        gender: to_candid_Gender_n47(_uploadFile, _downloadFile, value.gender)
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferences: Preferences;
    showAge: boolean;
    relationshipIntent: RelationshipIntent;
    shareCode: string;
}): {
    preferences: _Preferences;
    showAge: boolean;
    relationshipIntent: _RelationshipIntent;
    shareCode: string;
} {
    return {
        preferences: to_candid_Preferences_n43(_uploadFile, _downloadFile, value.preferences),
        showAge: value.showAge,
        relationshipIntent: to_candid_RelationshipIntent_n45(_uploadFile, _downloadFile, value.relationshipIntent),
        shareCode: value.shareCode
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    joy: null;
} | {
    sad: null;
} | {
    shy: null;
} | {
    zen: null;
} | {
    hopeful: null;
} | {
    inspiration: null;
} | {
    tired: null;
} | {
    content: null;
} | {
    anxious: null;
} | {
    courage: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    triumph: null;
} | {
    nervous: null;
} | {
    embarrass: null;
} | {
    apathetic: null;
} | {
    melancholy: null;
} | {
    bore: null;
} | {
    calm: null;
} | {
    fear: null;
} | {
    irritate: null;
} | {
    relaxed: null;
} | {
    grateful: null;
} | {
    lonely: null;
} | {
    secure: null;
} | {
    unsafe: null;
} | {
    satisfy: null;
} | {
    motivate: null;
} | {
    stressed: null;
} | {
    frustrate: null;
} | {
    overwhelm: null;
} | {
    passionate: null;
} | {
    disappoint: null;
} | {
    excited: null;
} | {
    indifferen: null;
} | {
    humbled: null;
} | {
    disgust: null;
} | {
    confident: null;
} | {
    curious: null;
} | {
    relieved: null;
} | {
    worry: null;
} | {
    guilty: null;
} | {
    ashamed: null;
} | {
    neutral: null;
} | {
    optimistic: null;
} {
    return value == Mood.joy ? {
        joy: null
    } : value == Mood.sad ? {
        sad: null
    } : value == Mood.shy ? {
        shy: null
    } : value == Mood.zen ? {
        zen: null
    } : value == Mood.hopeful ? {
        hopeful: null
    } : value == Mood.inspiration ? {
        inspiration: null
    } : value == Mood.tired ? {
        tired: null
    } : value == Mood.content ? {
        content: null
    } : value == Mood.anxious ? {
        anxious: null
    } : value == Mood.courage ? {
        courage: null
    } : value == Mood.happy ? {
        happy: null
    } : value == Mood.angry ? {
        angry: null
    } : value == Mood.triumph ? {
        triumph: null
    } : value == Mood.nervous ? {
        nervous: null
    } : value == Mood.embarrass ? {
        embarrass: null
    } : value == Mood.apathetic ? {
        apathetic: null
    } : value == Mood.melancholy ? {
        melancholy: null
    } : value == Mood.bore ? {
        bore: null
    } : value == Mood.calm ? {
        calm: null
    } : value == Mood.fear ? {
        fear: null
    } : value == Mood.irritate ? {
        irritate: null
    } : value == Mood.relaxed ? {
        relaxed: null
    } : value == Mood.grateful ? {
        grateful: null
    } : value == Mood.lonely ? {
        lonely: null
    } : value == Mood.secure ? {
        secure: null
    } : value == Mood.unsafe ? {
        unsafe: null
    } : value == Mood.satisfy ? {
        satisfy: null
    } : value == Mood.motivate ? {
        motivate: null
    } : value == Mood.stressed ? {
        stressed: null
    } : value == Mood.frustrate ? {
        frustrate: null
    } : value == Mood.overwhelm ? {
        overwhelm: null
    } : value == Mood.passionate ? {
        passionate: null
    } : value == Mood.disappoint ? {
        disappoint: null
    } : value == Mood.excited ? {
        excited: null
    } : value == Mood.indifferen ? {
        indifferen: null
    } : value == Mood.humbled ? {
        humbled: null
    } : value == Mood.disgust ? {
        disgust: null
    } : value == Mood.confident ? {
        confident: null
    } : value == Mood.curious ? {
        curious: null
    } : value == Mood.relieved ? {
        relieved: null
    } : value == Mood.worry ? {
        worry: null
    } : value == Mood.guilty ? {
        guilty: null
    } : value == Mood.ashamed ? {
        ashamed: null
    } : value == Mood.neutral ? {
        neutral: null
    } : value == Mood.optimistic ? {
        optimistic: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RelationshipIntent): {
    romantic: null;
} | {
    both: null;
} | {
    friendship: null;
} {
    return value == RelationshipIntent.romantic ? {
        romantic: null
    } : value == RelationshipIntent.both ? {
        both: null
    } : value == RelationshipIntent.friendship ? {
        friendship: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    nonBinary: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value == Gender.nonBinary ? {
        nonBinary: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "uploaded";
    uploaded: UploadedAvatar;
} | {
    __kind__: "systemAvatar";
    systemAvatar: string;
}): {
    uploaded: _UploadedAvatar;
} | {
    systemAvatar: string;
} {
    return value.__kind__ === "uploaded" ? {
        uploaded: value.uploaded
    } : value.__kind__ === "systemAvatar" ? {
        systemAvatar: value.systemAvatar
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
